### ISSUE TITLE
v1.4 release checklist

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#340]
#### wrap up work
* [x] close all issues/PRs related to `v1.4` or move to +1/`v2.0` release
    * [x] TSP notebook #330 (#342)/ #110 / #100 
      * [x] Use_case-tsp.ipynb
      * punt to `v2.0`
    * [x] figure out sphinx issue or punt to next release #339, #342 
* [x] review/rename/rerun notebooks
  * [x] remove/assimilate [Snapping_Demonstration.ipynb](https://github.com/pysal/spaghetti/blob/master/notebooks/Snapping_Demonstration.ipynb)
   * [x] rename ~~[Spaghetti_Pointpatterns_Empirical.ipynb](https://github.com/pysal/spaghetti/blob/master/notebooks/Spaghetti_Pointpatterns_Empirical.ipynb)~~ --> Basic_spaghetti_tutorial.ipynb
   * [x] rename ~~[Network_Usage.ipynb](https://github.com/pysal/spaghetti/blob/master/notebooks/Network_Usage.ipynb)~~ --> Advanced_spaghetti_tutorial.ipynb
  * [x] rename ~~[Facility_Location.ipynb](https://github.com/pysal/spaghetti/blob/master/notebooks/Facility_Location.ipynb)~~ --> Use_case-facility_location.ipynb
  * [x] uniform notebook layout
      * [x] standardize font
      * [x] disclaimer/citation
      * [x] Title/subtitle/author
      * [x] explanation/structure
      * [x] load watermark / system watermark
      * [x] notebook requirements
      * [x] (uniform) import structure
      * [x] watermark -iv
      * [x] nb_black formatting for cells
   * [x] update notebook links in `README.md`
   * [x] binderize notebooks in docs (see [`giddy`](https://giddy.readthedocs.io/en/latest/tutorial.html) for example)(also #78)
* [x] review `README.md` for references to version
  * [x] ~~python~~ --> Python

---------------------------------------------------------------
#### release `v1.4.0`
* [x] bump version in `__init__`
* [x] rerun `docsrc`
* [x] update CHANGELOG (automatic) **if needed**
* [x] release on `github`
* [x] release on `pypi`
* [x] release on `conda-forge`
   * [x] set [`sha256`](https://github.com/conda-forge/spaghetti-feedstock/blob/9839400d2564d17c404e6aff626388c881aa6a13/recipe/meta.yaml#L10) as a variable in the feedstock recipe (as is done in [`watermark-feedstock`](https://github.com/conda-forge/watermark-feedstock/blob/047b3788fb3076b63700cead651525ca226d5511/recipe/meta.yaml#L3)).
   * [x] update [`doc_url`](https://github.com/conda-forge/spaghetti-feedstock/blob/9839400d2564d17c404e6aff626388c881aa6a13/recipe/meta.yaml#L46) in the feedstock recipe
  * [x] update [`home`](https://github.com/conda-forge/spaghetti-feedstock/blob/9839400d2564d17c404e6aff626388c881aa6a13/recipe/meta.yaml#L34) in the feedstock recipe
  * [x] update [`description`](https://github.com/conda-forge/spaghetti-feedstock/blob/9839400d2564d17c404e6aff626388c881aa6a13/recipe/meta.yaml#L39) in the feedstock recipe
* [ ] ~~update CHANGELOG (manual)~~
---------------------------------------------------------------
#### ~~announce `v1.4.0`~~ save announcement for `v1.4.1` #365 
* [ ] ~~announce on `pysal/pysal.github.io`~~
* [ ] ~~announce on Twitter/LinkedIn/etc.~~
