### ISSUE TITLE
release v1.5.0

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spaghetti#450]
* Abandoning the `v1.4.3` and `v1.4.4` releases in favor of a `v1.5.0` release

### To Do

**wrap-up the following items**
* [x] **Refactor tests** #438  
    * [x] issue 1 (#439)
    * [x] issue 2 (#443)
 * [x] **Caveats Notebook** #426  
    * [x] build notebook
    * [x] rebuild docs
 * [x] ~~**g,f function correct?** #225~~
    * [x] ~~combine internal `gfunction()` and `ffunction()`~~
    * [x] ~~update doctring~~
 * [x] **Improved explanations/documentation**
    * [x] update doctrings / better explanations of Network-*K* function.
    * [x] add formulation into `network.NetworkK()`
    * [x] beef up notebook
       * [x] add interpretations to [Spatial network analysis](https://pysal.org/spaghetti/notebooks/network-analysis.html)
       * [x] visualize points and network
       * [x] regular lattice example and empirical example
   
 * [x] **Logo work** #448 
     * [x] update logo on the docs site
     * [x] ~~NumFocus logo?~~
 * [x] **Vertex coordinate precision relaxation**
   * [x] this is tied in with #445 
 * [x] **Spanning Trees** #449, #459 
    * [x] MST functionality
    * [x] MST references
    * [x] MST notebook
    * [x] MST tests
    * [x] add MST to API docs
    * [x] swap out `README` plot? — pruned out `streets` data: 800x400?
* [x] **GitHub Actions**
   * [x] Migrate to GitHub Actions and drop Travis/Appveyor #452 #453 
* [x] **Network spatial weights notebook** #457 
    * [x] short demo — streets: "advanced" functionality?
 * [x] **Review/Confirm or Refactor NetworkK** #101
    * All's well here. See #465 
 * [x] **update docs as needed**

------------

**release `v1.5.0.rc0--x`**

* [x] version bump
* [x] change log
* [x] GitHub release
* [x] PyPI release
* [x] conda-forge release

------------

* [x] auto release GHA #487 
  * see:
    * pysal/submodule_template#29
    * spatialucr/geosnap#221

-----------------

**release `v1.5.0`**

* [x] version bump
* [x] update `CHANGELOG.md`
* [x] ~~GitHub release~~
* [x] ~~PyPI release~~
* [x] conda-forge release

------------------
**announce `v1.5.0`**
* [x] announce on `pysal/pysal.github.io`
* [x] announce on Twitter/LinkedIn/etc.
